In [86]:
from numpy import array,arange, reshape, linspace,resize,ones, vstack, hstack, dtype

In [20]:
mylist = [1,2,3,4,4,5,6,2,23,5,56]
a = array(mylist)
ch = [chr(x) for x in range(60,80)]
b = [ x for x in range(14)]
a = array([mylist,b])
ch = [chr(x) for x in range(60,80)]
a.shape
print(a)
ch = [chr(x) for x in range(60,80)]
a.shape

[list([1, 2, 3, 4, 4, 5, 6, 2, 23, 5, 56])
 list([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])]


(2,)

In [26]:
c = array([[234,2424],[2424,323]])
c

array([[ 234, 2424],
       [2424,  323]])

In [27]:
c.shape

(2, 2)

In [42]:
dw = arange(0,24,2)
len(dw)

12

In [55]:
dw =dw.reshape(2,6)
dw

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [56]:
dw[0,] =linspace(40,24,6)

In [57]:
dw

array([[40, 36, 33, 30, 27, 24],
       [12, 14, 16, 18, 20, 22]])

In [62]:
dw.resize(3,4)
dw

array([[40, 36, 33, 30],
       [27, 24, 12, 14],
       [16, 18, 20, 22]])

In [66]:
onesa = ones((3,4))

In [67]:
dw = dw + onesa
dw

array([[ 41.,  37.,  34.,  31.],
       [ 28.,  25.,  13.,  15.],
       [ 17.,  19.,  21.,  23.]])

In [73]:
dw = vstack([dw,dw*2])

In [74]:
dw

array([[  82.,   74.,   68.,   62.],
       [  56.,   50.,   26.,   30.],
       [  34.,   38.,   42.,   46.],
       [ 164.,  148.,  136.,  124.],
       [ 112.,  100.,   52.,   60.],
       [  68.,   76.,   84.,   92.]])

In [76]:
dw = hstack([dw,dw*2])

In [78]:
print(dw**2)

[[   6724.    5476.    4624.    3844.   26896.   21904.   18496.   15376.]
 [   3136.    2500.     676.     900.   12544.   10000.    2704.    3600.]
 [   1156.    1444.    1764.    2116.    4624.    5776.    7056.    8464.]
 [  26896.   21904.   18496.   15376.  107584.   87616.   73984.   61504.]
 [  12544.   10000.    2704.    3600.   50176.   40000.   10816.   14400.]
 [   4624.    5776.    7056.    8464.   18496.   23104.   28224.   33856.]]


In [79]:
dw.shape

(6, 8)

In [80]:
dw.T

array([[  82.,   56.,   34.,  164.,  112.,   68.],
       [  74.,   50.,   38.,  148.,  100.,   76.],
       [  68.,   26.,   42.,  136.,   52.,   84.],
       [  62.,   30.,   46.,  124.,   60.,   92.],
       [ 164.,  112.,   68.,  328.,  224.,  136.],
       [ 148.,  100.,   76.,  296.,  200.,  152.],
       [ 136.,   52.,   84.,  272.,  104.,  168.],
       [ 124.,   60.,   92.,  248.,  120.,  184.]])

In [81]:
dw.shape

(6, 8)

In [82]:
dw.T.shape

(8, 6)

In [88]:
dw.dtype

dtype('float64')

In [92]:
dw = (dw) /2
dw

array([[  2.26060880e+07,   1.49932880e+07,   1.06906880e+07,
          7.38816800e+06,   3.61697408e+08,   2.39892608e+08,
          1.71051008e+08,   1.18210688e+08],
       [  4.91724800e+06,   3.12500000e+06,   2.28488000e+05,
          4.05000000e+05,   7.86759680e+07,   5.00000000e+07,
          3.65580800e+06,   6.48000000e+06],
       [  6.68168000e+05,   1.04256800e+06,   1.55584800e+06,
          2.23872800e+06,   1.06906880e+07,   1.66810880e+07,
          2.48935680e+07,   3.58196480e+07],
       [  3.61697408e+08,   2.39892608e+08,   1.71051008e+08,
          1.18210688e+08,   5.78715853e+09,   3.83828173e+09,
          2.73681613e+09,   1.89137101e+09],
       [  7.86759680e+07,   5.00000000e+07,   3.65580800e+06,
          6.48000000e+06,   1.25881549e+09,   8.00000000e+08,
          5.84929280e+07,   1.03680000e+08],
       [  1.06906880e+07,   1.66810880e+07,   2.48935680e+07,
          3.58196480e+07,   1.71051008e+08,   2.66897408e+08,
          3.98297088e+08,   5.7

In [104]:
dw[-2::-2,].max()

1258815488.0

In [106]:
dw[2,3:5]

array([  2238728.,  10690688.])

In [110]:
ar2 = arange(36)
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [116]:
ar2.resize((6,6))

In [117]:
ar2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [123]:
ar2[::,1::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [125]:
ar2[ar2>10] = 0
ar2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [126]:
ar3 = ar2[::,1::2]
ar3

array([[1, 3, 5],
       [7, 9, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [127]:
ar3[0,:] = 0

In [128]:
ar3

array([[0, 0, 0],
       [7, 9, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [129]:
ar2

array([[ 0,  0,  2,  0,  4,  0],
       [ 6,  7,  8,  9, 10,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [130]:
ar4 = ar2.copy()

In [131]:
ar4

array([[ 0,  0,  2,  0,  4,  0],
       [ 6,  7,  8,  9, 10,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [132]:
ar4[ar4==0] = 10

In [133]:
ar4

array([[10, 10,  2, 10,  4, 10],
       [ 6,  7,  8,  9, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [134]:
ar3

array([[0, 0, 0],
       [7, 9, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [135]:
for x in ar4:
    print(x)

[10 10  2 10  4 10]
[ 6  7  8  9 10 10]
[10 10 10 10 10 10]
[10 10 10 10 10 10]
[10 10 10 10 10 10]
[10 10 10 10 10 10]


In [137]:
for x in range(len(ar4)):
    print(ar4[x])

[10 10  2 10  4 10]
[ 6  7  8  9 10 10]
[10 10 10 10 10 10]
[10 10 10 10 10 10]
[10 10 10 10 10 10]
[10 10 10 10 10 10]


In [138]:
for r,c in enumerate(ar4):
    print(r,c)

0 [10 10  2 10  4 10]
1 [ 6  7  8  9 10 10]
2 [10 10 10 10 10 10]
3 [10 10 10 10 10 10]
4 [10 10 10 10 10 10]
5 [10 10 10 10 10 10]
